### ISSUE TITLE
Super class does not exist

### ISSUE THREAD

**Issue by Lehmann-Fabian** [nextflow-io/nf-hello#10]
The file [HelloExtension.groovy](https://github.com/nextflow-io/nf-hello/blob/master/plugins/nf-hello/src/main/nextflow/hello/HelloExtension.groovy) extends PluginExtensionPoint, which no longer exists in Nextflow.

**Comment by pditommaso** [comment]
That's defined in the core nextflow https://github.com/nextflow-io/nextflow/blob/fab6bd5e6b23fd7fcae73b2e44559402d2eab920/modules/nextflow/src/main/groovy/nextflow/plugin/extension/PluginExtensionPoint.groovy#L33-L33

**Comment by Lehmann-Fabian** [comment]
Right... I forgot to update the master branch in this environment.
